parser: 'babel-eslint'

extends:
  - fbjs
  - prettier
  - prettier/flowtype
  - prettier/react

plugins:
  - prettier

rules:
  prettier/prettier:
    - error
    -
      singleQuote: true
      trailingComma: es5
      bracketSpacing: false
      jsxBracketSameLine: false
      parser: flow
  max-len:
    - error
    -
      code: 120
      ignoreUrls: true
  no-confusing-arrow: error
  no-mixed-operators: error
  no-unexpected-multiline: error
