version: '3'
services:
  golang:
    build:
      context: .
      args:
        USER: $USER
        UID: $UID
    image: golang-app
    volumes:
      - ./go:/go
    command: sh ./start.sh
    env_file:
      - .env
    ports:
      - 8080:8080
    links:
      - mysql
    container_name: lovechan_api
  mysql:
    image: mysql:5.7
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=lovechan
        - MYSQL_USER=lovechan
        - MYSQL_PASSWORD=password
    ports:
        - 3306:3306
    env_file:
      - .env_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: lovechan_mysql


