version: 2
jobs :
  build:
    docker:
      - image: node:8.9.0-alpine

    working_directory: /root/project/client

    branches:
      only:
        - /squawknhart-.*/
        - master

    steps:
      - add_ssh_keys:
          fingerprints:
            - "76:bd:2c:3f:42:32:28:99:57:01:2c:1f:b9:ee:20:60"

      - checkout

      - restore_cache:
          key: lovechan-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: machine info
          command:
            source /root/.bashrc &&
            echo "node $(node -v)\"
            echo "yarn $(yarn --version)\"

      - run:
          name: install dependencies
          command: yarn

      - run:
          name: build
          command: yarn build

      - save_cache:
          key: lovechan-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - /root/project/client/node_modules
            - /root/project/.cache/yarn
