version: 2
jobs :
  build:
    docker:
      - image: node:8.9.0-alpine

    working_directory: /home/node

    branches:
      only:
        - /squawknhart-.*/
        - master

    steps:
      - checkout

      - restore_cache:
          key: lovechan-{{ .Branch }}-{{ checksum "client/yarn.lock" }}

      - run:
          name: check machine ENV
          command:
            source /root/.bashrc &&
            echo "node $(node -v)\"
            echo "yarn $(yarn --version)\"

      - run:
          name: install dependencies
          command: yarn

      - run:
          name: build
          command: yarn build

      - save_cache:
          key: lovechan-{{ .Branch }}-{{ checksum "client/yarn.lock" }}
          paths:
            - ~/.cache/yarn
