
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  revision = "0000b0d6fa546d549886da15ef182437222add59"
  name = "github.com/deadcheat/goacors"

[[constraint]]
  revision = "4cfe9e5eb207f854100aac4a3e8eaf9c0aada4b1"
  name = "github.com/goadesign/goa"

[[constraint]]
  version = "v0.16.0"
  name = "github.com/GoogleCloudPlatform/google-cloud-go"

[[constraint]]
  revision = "99f3ad6d85ae53d0fecf788ab62d0e9734b3c117"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  revision = "b89020ee79b89a7f932c5617d218fc06db382f53"
  name = "github.com/gorilla/websocket"
